language: php

php:
  - '7.0'
  - '5.6'
  - '5.5'
  - '5.4'

before_script:
  - composer install
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - composer global require "squizlabs/php_codesniffer=*"

script:
  - vendor/bin/phpunit
  - vendor/bin/behat
  - phpcs --standard=PSR2 --colors
