language: php

php:
  - '7.0'
  - '5.6'
  - '5.5'
  - '5.4'

before_script:
  - composer install
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - vendor/bin/phpunit
  - vendor/bin/behat
  - phpcs --standard=PSR2 --colors
