version: "3"

services:
  nginx:
    build:
      context: ./.docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${APPLICATION}:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/app.ini:/usr/local/etc/php/conf.d/php.ini
      - ${APPLICATION}:/var/www
    expose:
      - 9000
    environment:
      - PS_USER_EMAIL=${PS_USER_EMAIL}
      - PS_USER_TOKEN=${PS_USER_TOKEN}
      - PS_APPID=${PS_APPID}
      - PS_APPKEY=${PS_APPKEY}
      - PS_ENVIRONMENT=${PS_ENVIRONMENT}